name: comment
on:
  workflow_call:
  check_run:
  pull_request_review:
  pull_request_review_comment:
  issue_comment:
  pull_request_target:
  workflow_run:
    workflows: ["default2"]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          NUMBER: ${{ github.event.number }}
          HEAD_REF: ${{ github.head_ref }}
          HEADDOTREF: ${{ github.event.pull_request.head.ref }}
          HEADSHA: ${{ github.event.pull_request.head.sha }}
          PULLREQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "github.event.number is $NUMBER"
          echo "github.head_ref is $HEAD_REF"
          echo "github.event.pull_request.head.ref is $HEADDOTREF"
          echo "github.event.pull_request.head.sha is $HEADSHA"
          echo "github.event.pull_request.number is $PULLREQUEST_NUMBER"
          echo "$GITHUB_CONTEXT"
