name: default4
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(github.event.issue.title)}} blabla'
          echo "${{ toJSON(github.event.issue.title)}} dfdfd"
