name: default
on:
  pull_request_target:
    types: labeled
jobs:
  build:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      #- run: sleep 60
      - name: dump
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "test"          
          echo "$GITHUB_CONTEXT"
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - run: cat ./README.md
