on: pull_request

jobs:
  poison:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/poison
          key: poison_key
      - run: |
          cat poison
